services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: smartenergy-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://127.0.0.1:8000
    container_name: smartenergy-frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend